### ISSUE TITLE
Verify features

### ISSUE THREAD

**Issue by JordanAnthonyKing** [kiennq/treesit-langs#3]
Hi, I’ve added angular support on my fork https://github.com/JordanAnthonyKing/treesit-langs 
I’ve got a defined angular-ts-mode that just derives from html-ts-modr in my config too as one doesn’t actually exist yet but I can’t tell if the highlighting I’ve added is taking effect. There’s nothing to call or activate so how can I verify?

**Comment by kiennq** [comment]
There is `M-x treesit-hl-toggle` that you can use to verify if the highlighting is taking effect.
Optionally run `M-x font-lock-debug-fontify` after the previous command to make sure the highlighting is really taking effect.

Btw, my config for this package is
``` elisp
    (use-package treesit-langs
      :quelpa (treesit-langs :repo "kiennq/treesit-langs"
                             :fetcher github-ssh
                             :files ("treesit-*.el" "queries")
                             :version-type elpa)
      :defer t
      :hook ((prog-mode text-mode conf-mode)
             . (lambda ()
                 ;; some mode is better be highlighted not using tree-sitter
                 (unless (member major-mode '(sh-mode))
                   (ignore-errors (treesit-hl-toggle 'on)))))
      :custom
      (treesit-langs-git-dir nil)
      (treesit-langs-grammar-dir (expand-file-name "tree-sitter" user-emacs-directory))
      :init
      :config
      (add-to-list 'treesit-extra-load-path treesit-langs-grammar-dir))
```

**Comment by JordanAnthonyKing** [comment]
This does work but now I find tab is broken, i.e. pressing tab on a new line isn't indenting me to the correct point (or doing anything really). I assume this is because the base treesitter mode's description for how to tab is being overridden. Is there a workaround?

**Comment by kiennq** [comment]
This package doesn't define indent rules so we will need to either rely on the current major mode's indent rules or define a new `treesit-simple-indent-rules`.

Btw, here is the indent rules for `html-ts-mode`

``` elisp
(defvar html-ts-mode--indent-rules
  `((html
     ((parent-is "fragment") column-0 0)
     ((node-is "/>") parent-bol 0)
     ((node-is ">") parent-bol 0)
     ((node-is "end_tag") parent-bol 0)
     ((parent-is "comment") prev-adaptive-prefix 0)
     ((parent-is "element") parent-bol html-ts-mode-indent-offset)
     ((parent-is "script_element") parent-bol html-ts-mode-indent-offset)
     ((parent-is "style_element") parent-bol html-ts-mode-indent-offset)
     ((parent-is "start_tag") parent-bol html-ts-mode-indent-offset)
     ((parent-is "self_closing_tag") parent-bol html-ts-mode-indent-offset)))
  "Tree-sitter indent rules.")
```

**Comment by JordanAnthonyKing** [comment]
I understand that, I’m just curious as to how to enable them. They’re broken for me in typescript too.

**Comment by kiennq** [comment]
Maybe I misunderstood the issue? Do you mean that after running `M-x treesit-hl-toggle`, you get the new highlightings but the tab indentation is broken?
It shouldn't though as the indentation should be kept from the current major-mode

**Comment by JordanAnthonyKing** [comment]
> Maybe I misunderstood the issue? Do you mean that after running `M-x treesit-hl-toggle`, you get the new highlightings but the tab indentation is broken? It shouldn't though as the indentation should be kept from the current major-mode

I do believe that that is what is happening yes. Let me verify however later in the day.

**Comment by kiennq** [comment]
Please check the value of the `indent-region-function` before and after run the `M-x treesit-hl-toggle`, it shouldn't be changed.

**Comment by JordanAnthonyKing** [comment]
Sorry for the delay, I can confirm that indentation is broken after enabling highlighting however the indent-region-function is the same both before and after.

Tested on your latest emacs build. (Thanks by the way).

**Comment by kiennq** [comment]
> Sorry for the delay, I can confirm that indentation is broken after enabling highlighting however the indent-region-function is the same both before and after.
> 
> Tested on your latest emacs build. (Thanks by the way).

Interesting, how about `indent-line-function`? If both are still the same then I don't know why the indentation can be broken. It's being dictated by these two functions only.
If you have a simple repro steps, I can try as well.

**Comment by JordanAnthonyKing** [comment]
indent-line-function is actually undefined after activating treesit-hl-toggle. It stays undefined until toggling highlighting off and switching buffer/window. Oddly this is only happening for me in typescript, html is fine.

I've noticed weirdness with typescript-ts-mode with other packages, maybe it relates to typescript-ts-base-mode?

**Comment by kiennq** [comment]
The reason is because the language alist is wrongly set for `typescript-ts-mode` to `tsx`. I've pushed a new change, can you try to see if it's fixed for you?

**Comment by JordanAnthonyKing** [comment]
This is working well for me now. I've got angular support working well on my fork.

One weird thing though, if I hook my `angular-ts-mode` with `treesit-hl-toggle` I see 'disabling highlighting' echoed in the minibuffer and there's no highlighting (provided by this package). If I don't hook I also don't see any highlighting. Either way I have to call the function manually.

Am I misunderstanding something here?

**Comment by kiennq** [comment]
Can you try with the latest version to see if it's working?

**Comment by JordanAnthonyKing** [comment]
Yeah I'm still seeing the issue, I have to manually call treesite-hl-toggle.

```
(use-package treesit-langs
  :ensure (treesit-langs
           :host github
           :repo "JordanAnthonyKing/treesit-langs"
           :files ("treesit-*.el" "queries"))
  :defer t
  :hook ((angular-ts-mode typescript-ts-mode) . treesit-hl-toggle)
  :custom
  (treesit-langs-git-dir nil)
  (treesit-langs-grammar-dir (expand-file-name "tree-sitter" user-emacs-directory))
  :config
  (add-to-list 'treesit-extra-load-path treesit-langs-grammar-dir))
```

**Comment by kiennq** [comment]
Oh, I see why now. You need to call `(treesit-hl-toggle 'on)` instead.

**Comment by kiennq** [comment]
> I notice as well however that nvim-treesitter provides a set of indentation specs as well as highlighting. Maybe we can translate those too?

If that's possible it would be great.
This package right now only configures highlighting and forgoes of indentation so it should use whichever indentation is there in the original major mode
